In [1]:
import math
import warnings
import numpy as np
import pandas as pd
from CF import get_CF
warnings.filterwarnings("error")

In [ ]:
def NMF(V, r):
    m,n = V.shape
    W = np.ones((m,r))
    H = np.ones((r,n))
    for i in range(1000):
        try:
            W, H = W * np.matmul(V,H.T) / ((np.matmul(np.matmul(W,H),H.T) + np.ones((m,r)))/1000), H * np.matmul(W.T,V)/ (np.matmul(np.matmul(W.T,W),H) + np.ones((r,n))/1000)
        except:
            print (W)
            print (H)
            break
    return W,H

In [ ]:
CF = get_CF()
W,H = NMF(CF, 30)

In [16]:
a = np.array(range(2*2*4))
a = a.reshape((2,2,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [17]:
a.reshape((-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.maximum(a, 3)

array([[[ 3,  3,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])